import 'package:flutter/material.dart';
import '../../../core/constants/app_colors.dart';
import '../../../core/widgets/app_card.dart';
import '../../../models/patient_brief_model.dart';
import '../../../services/health_continuity_service.dart';

/// AI Patient Brief card — displayed on the doctor's patient detail screen.
/// Shows a collapsible structured clinical summary generated by the Health Continuity Engine.
class AiPatientBriefCard extends StatefulWidget {
  final int consultationId;
  final PatientBriefModel? initialBrief;

  const AiPatientBriefCard({
    super.key,
    required this.consultationId,
    this.initialBrief,
  });

  @override
  State<AiPatientBriefCard> createState() => _AiPatientBriefCardState();
}

class _AiPatientBriefCardState extends State<AiPatientBriefCard> {
  final HealthContinuityService _service = HealthContinuityService();
  PatientBriefModel? _brief;
  bool _isLoading = false;
  bool _isExpanded = true;

  @override
  void initState() {
    super.initState();
    _brief = widget.initialBrief;
    if (_brief == null) {
      _loadBrief();
    }
  }

  Future<void> _loadBrief() async {
    setState(() => _isLoading = true);
    final brief = await _service.fetchPatientBrief(widget.consultationId);
    if (mounted) {
      setState(() {
        _brief = brief;
        _isLoading = false;
      });
    }
  }

  Future<void> _regenerateBrief() async {
    setState(() => _isLoading = true);
    final brief = await _service.generatePatientBrief(widget.consultationId);
    if (mounted) {
      setState(() {
        _brief = brief;
        _isLoading = false;
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        // Section Header
        Row(
          mainAxisAlignment: MainAxisAlignment.spaceBetween,
          children: [
            const Row(
              children: [
                Icon(Icons.assignment_outlined, size: 18, color: AppColors.primary),
                SizedBox(width: 8),
                Text(
                  'AI Patient Brief',
                  style: TextStyle(
                    fontSize: 16,
                    fontWeight: FontWeight.w800,
                    color: AppColors.textPrimary,
                  ),
                ),
              ],
            ),
            Row(
              children: [
                IconButton(
                  icon: const Icon(Icons.refresh, size: 18, color: AppColors.primary),
                  tooltip: 'Regenerate Brief',
                  onPressed: _isLoading ? null : _regenerateBrief,
                ),
                IconButton(
                  icon: Icon(
                    _isExpanded ? Icons.expand_less : Icons.expand_more,
                    size: 22,
                    color: AppColors.textSecondary,
                  ),
                  onPressed: () => setState(() => _isExpanded = !_isExpanded),
                ),
              ],
            ),
          ],
        ),
        const SizedBox(height: 4),

        if (_isLoading)
          const AppCard(
            padding: EdgeInsets.all(20),
            child: Center(
              child: Column(
                children: [
                  SizedBox(
                    height: 24,
                    width: 24,
                    child: CircularProgressIndicator(strokeWidth: 2.5, color: AppColors.primary),
                  ),
                  SizedBox(height: 10),
                  Text(
                    'Generating AI Patient Brief...',
                    style: TextStyle(fontSize: 12, color: AppColors.textSecondary),
                  ),
                ],
              ),
            ),
          )
        else if (_brief != null)
          AppCard(
            padding: const EdgeInsets.all(16),
            backgroundColor: AppColors.primaryContainer.withOpacity(0.25),
            borderColor: AppColors.primaryLight.withOpacity(0.3),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                // Emergency banner detection
                if (_brief!.briefText.startsWith('🚨'))
                  Container(
                    width: double.infinity,
                    padding: const EdgeInsets.all(10),
                    margin: const EdgeInsets.only(bottom: 10),
                    decoration: BoxDecoration(
                      color: AppColors.emergencyLight,
                      borderRadius: BorderRadius.circular(8),
                    ),
                    child: const Row(
                      children: [
                        Icon(Icons.warning_amber_rounded, size: 18, color: AppColors.emergencyDark),
                        SizedBox(width: 8),
                        Expanded(
                          child: Text(
                            'HIGH RISK — Emergency symptoms detected',
                            style: TextStyle(
                              fontSize: 12,
                              fontWeight: FontWeight.w700,
                              color: AppColors.emergencyDark,
                            ),
                          ),
                        ),
                      ],
                    ),
                  ),

                // Chief Complaint
                if (_brief!.chiefComplaint.isNotEmpty) ...[
                  _buildLabel('Chief Complaint'),
                  const SizedBox(height: 2),
                  Text(
                    _brief!.chiefComplaint,
                    style: const TextStyle(fontSize: 13, fontWeight: FontWeight.w600, color: AppColors.textPrimary),
                  ),
                  const SizedBox(height: 10),
                ],

                // Expandable details
                if (_isExpanded) ...[
                  // Risk Factors
                  if (_brief!.riskFactors.isNotEmpty) ...[
                    _buildLabel('Risk Factors'),
                    const SizedBox(height: 4),
                    ..._brief!.riskFactors.map(
                      (f) => Padding(
                        padding: const EdgeInsets.only(bottom: 3),
                        child: Text('• $f', style: const TextStyle(fontSize: 12, color: AppColors.textPrimary)),
                      ),
                    ),
                    const SizedBox(height: 8),
                  ],

                  // Allergies
                  if (_brief!.allergiesAndContraindications.isNotEmpty &&
                      _brief!.allergiesAndContraindications.toLowerCase() != 'none known' &&
                      _brief!.allergiesAndContraindications.toLowerCase() != 'none') ...[
                    _buildLabel('Allergies & Contraindications'),
                    const SizedBox(height: 2),
                    Text(
                      _brief!.allergiesAndContraindications,
                      style: const TextStyle(fontSize: 12, color: AppColors.emergency, fontWeight: FontWeight.w600),
                    ),
                    const SizedBox(height: 8),
                  ],

                  // AI Triage Assessment
                  if (_brief!.aiTriageAssessment.isNotEmpty) ...[
                    _buildLabel('AI Triage Assessment'),
                    const SizedBox(height: 2),
                    Text(
                      _brief!.aiTriageAssessment,
                      style: const TextStyle(fontSize: 12, color: AppColors.textSecondary, height: 1.4),
                    ),
                    const SizedBox(height: 8),
                  ],

                  // Suggested Focus Areas
                  if (_brief!.suggestedFocusAreas.isNotEmpty) ...[
                    _buildLabel('Suggested Focus Areas'),
                    const SizedBox(height: 4),
                    Wrap(
                      spacing: 6,
                      runSpacing: 6,
                      children: _brief!.suggestedFocusAreas.map(
                        (area) => Container(
                          padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 5),
                          decoration: BoxDecoration(
                            color: AppColors.primary.withOpacity(0.1),
                            borderRadius: BorderRadius.circular(20),
                          ),
                          child: Text(
                            area,
                            style: const TextStyle(fontSize: 11, fontWeight: FontWeight.w600, color: AppColors.primary),
                          ),
                        ),
                      ).toList(),
                    ),
                    const SizedBox(height: 8),
                  ],

                  // Source badge
                  Align(
                    alignment: Alignment.bottomRight,
                    child: Container(
                      padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 3),
                      decoration: BoxDecoration(
                        color: _brief!.source == 'google_gemini_api'
                            ? AppColors.successLight
                            : AppColors.warningLight,
                        borderRadius: BorderRadius.circular(10),
                      ),
                      child: Text(
                        _brief!.source == 'google_gemini_api' ? 'AI Generated' : 'Offline Template',
                        style: TextStyle(
                          fontSize: 10,
                          fontWeight: FontWeight.w600,
                          color: _brief!.source == 'google_gemini_api'
                              ? AppColors.successDark
                              : AppColors.warningDark,
                        ),
                      ),
                    ),
                  ),
                ],
              ],
            ),
          )
        else
          AppCard(
            padding: const EdgeInsets.all(14),
            child: Center(
              child: Text(
                'No patient brief available. Tap refresh to generate.',
                style: TextStyle(fontSize: 12, color: AppColors.textMuted),
              ),
            ),
          ),
      ],
    );
  }

  Widget _buildLabel(String text) {
    return Text(
      text,
      style: const TextStyle(
        fontSize: 12,
        fontWeight: FontWeight.w700,
        color: AppColors.textSecondary,
      ),
    );
  }
}
